version: '3.8'

services:
  Tier2-server:
    restart: 'no'
    ports:
      - 8017:80
      - 44317:443
    command: >
      sh -c "dotnet dev-certs https -ep /https/aspnetapp.pfx -p "test" &&
      dotnet dev-certs https --trust"
    environment:
      HTTPS_PORT: 44317
      HTTP_PORT: 8017
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_ADDITIONAL_APPSETTINGS: Local
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: test
      DATABASE_CONNECTION_STRING: Host=rest-server-db_dev-local;Database=RestServerDB;Username=root;Password=Localonly123;

  Tier2-server-db:
    container_name: Tier2-server-db_dev-local
    restart: 'no'
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: Localonly123