trigger:
  branches:
    include:
      - '*'
    exclude:
      - master
      - releases/*

pool:
  name: UbuntuDockerAgents

stages:
  - stage:
    jobs:
      - job: Build_docker_image
        steps:
          - template: ../tasks/build.yml
          - template: ../tasks/install_docker.yml
          - template: ../tasks/build_docker_image.yml