trigger:
  branches:
    include:
    exclude:
      - '*'
  paths:
    exclude:
      - master
      - releases/*
      - '*'



pr:
  branches:
    include:
      - '*'

pool:
  vmImage: ubuntu-latest

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
  - stage:
    jobs:
      - job: Tier2_CI
        steps:
          - template: ../tasks/build.yml
          - template: ../tasks/test.yml