version: '3.8'

services:
  tier2-server:
    container_name: tier2-server_dev-local
    restart: 'no'
    ports:
      - 8017:80
      - 44317:443
    environment:
      HTTPS_PORT: 44317
      HTTP_PORT: 8017
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_ADDITIONAL_APPSETTINGS: Local