version: '3.8'

services:
  tier2-server:
    container_name: tier2-server_${ENV:-}
    build:
      context: .
      dockerfile: ../RestServer/Dockerfile
      target: final
    restart: unless-stopped
    environment:
      ASPNETCORE_URLS: https://+:443;https://+:80
      ASPNETCORE_ENVIRONMENT: ${ASP_ENV:-}