version: '3.8'

services:
  tier2-server-test:
    container_name: tier2-server-test
    build:
      context: .
      dockerfile: ../RestServer/Dockerfile
      target: test
    entrypoint: [ "dotnet", "test", "UnitTest.csproj", "--no-restore", "--configuration", "Release", "--results-directory", "/tests", "--logger", "trx;LogFileName=test-results.trx", "--collect:\"XPlat Code Coverage\"" ]
    volumes:
      - testResultVolume:/tests:rw
      
volumes:
  testResultVolume:
    name: testResultVolume_${TAG}
    external: false