steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk'
    inputs:
      packageType: sdk
      version: 7.0.402
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: 'build'
      projects: '*.sln'
      arguments: --configuration Release