steps:
  - task: UseDotNet@2
    inputs:
      version: '7.x'
  
  - task: NuGetToolInstaller@1
    
  - task: DotNetCoreCLI@2
    displayName: 'Restore NuGet Packages'
    inputs:
      command: 'restore'
      projects: '$(solution)'
      feedsToUse: 'select'

  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs:
      command: 'build'
      projects: '$(solution)'
      arguments: '--configuration $(buildConfiguration)'
      zipAfterPublish: true  # Optional: zips the published output for easier deployment
      modifyOutputPath: false  # Optional: keeps the default output path