steps:
  - task: UseDotNet@2
    inputs:
      version: '7.x'
  
  - task: NuGetToolInstaller@1
    
  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)'
  
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '$(solution)'
      arguments: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"' # Update this to match your need
      configuration: '$(buildConfiguration)'